### ISSUE TITLE
Two minor bugs

### ISSUE THREAD

**Issue by jnktsj** [yupenghe/methylpy#1]
Hi, I found two minor bugs in `call_mc.py` although the bugs wouldn't affect the results much:
* Line 2,746 in "call_methylated_sites"
`avg_qual = total_phred / total_bases` --> `avg_qual = total_phred / float(total_bases)`

* Line 3,069 in "benjamini_hochberg_correction_call_methylated_sites"
`bh_value = float(fields[6]) * mc_class_counts[fields[3]] / (test_num[fields[3] + 1)` --> `bh_value = float(fields[6]) * mc_class_counts[fields[3]] / test_num[fields[3]`

**Comment by yupenghe** [comment]
Thanks! Sorry for late response. I will make the revision.
