### ISSUE TITLE
ValueError when mapping samples

### ISSUE THREAD

**Issue by williamtjordan** [yupenghe/methylpy#11]
Hello, 
I have been getting ValueErrors when I attempt to map samples using methylpy 1.3.2 during the sorting steps after SAM file creation.

I have attached two examples of the error file output.  Any help in how I can resolve this error would be most appreciated.

[error_methylpy2.txt](https://github.com/yupenghe/methylpy/files/2007091/error_methylpy2.txt)
[error_methylpy.txt](https://github.com/yupenghe/methylpy/files/2007092/error_methylpy.txt)

Thank you!

**Comment by yupenghe** [comment]
Hi,
I will look into the error but I need more information.

Could you please share the command you ran? Also, can you do "ls -hltr" in the working directory? It is helpful to know what files are generated and their file size. 

It will be greatly helpful if you can reproduce the error with a small fastq. 

Yupeng

**Comment by yupenghe** [comment]
Also, can you [test methylpy](https://github.com/yupenghe/methylpy#test-methylpy) using the below command? If all tests are passed, your installation should be fine and then it is probably issue in the input format.

```bash
wget http://neomorph.salk.edu/yupeng/share/methylpy_test.tar.gz
tar -xf methylpy_test.tar.gz
cd methylpy_test/
python run_test.py
```

**Comment by williamtjordan** [comment]
Hi Yupeng, 

Re-installing methylpy appears to have fixed the error, as it did not pass the installation test the first time.  

Thanks for your help!

**Comment by yupenghe** [comment]
Great!
