### ISSUE TITLE
Error compiling rms.cpp in MacOS high sierra

### ISSUE THREAD

**Issue by shahsam** [yupenghe/methylpy#13]
Hi Yupeng, I am now trying to compile the rms.cpp but it's not working in my system, could you help to figure out the problem? I installed gsl in /usr/local/, when I run the code provided in the tutorial, it could not locate gsl:

```
 g++ -O3 -l gsl -l gslcblas -o run_rms_tests.out rms.cpp
rms.cpp:17:10: fatal error: 'gsl/gsl_rng.h' file not found
#include <gsl/gsl_rng.h>
         ^~~~~~~~~~~~~~~
1 error generated.
```
Then I tried specifying the path for gsl header files, but this produces another error:

```
$g++ -O3 -I /usr/local/include -L /usr/local/lib -l gsl -l gslcblas -o run_rms_tests.out rms.cpp
rms.cpp:88:1: warning: control reaches end of non-void function [-Wreturn-type]
}
^
1 warning generated.
```

**Comment by yupenghe** [comment]
Hi, 
You including the path to gsl header files seems to work with a warning. Is the run_rms_tests.out file generated? If you run `./run_rms_tests.out`, can you see the help information? 

Yupeng

**Comment by shahsam** [comment]
Hi Yupeng, yes I can see the help information now, and I ran DMRfind without any issues. Thanks!
