### ISSUE TITLE
Running binomial tests per position seems random

### ISSUE THREAD

**Issue by rbpisupati** [yupenghe/methylpy#15]
Hi Yupeng, 

I am running methylpy on sample and the way methylation calling seems a bit random (in the table below check positions Chr1:102 and Chr1:107. Both are covered by only 1 read but still they are counted as methylated.)

> Chr1	101	+	CCT 	0	1	0
> Chr1	102	+	CTA 	1	1	1
> Chr1	107	+	CCC	1	1	0
> Chr1	108	+	CCG	1	1	1
> Chr1	109	+	CGA	1	2	1
> Chr1	110	-	CGG	5	5	1
> Chr1	114	+	CCG	2	2	1
> Chr1	115	+	CGG	2	2	1
> Chr1	116	-	CGG	6	7	1
> Chr1	117	-	CCG	1	7	0

The methylpy version I am using is 1.1.9, is it resolved in the newer versions? 

Rahul

**Comment by yupenghe** [comment]
What did you use as unmethylated control? Can you check the methylation of
it?

**Comment by rbpisupati** [comment]
I used chroloplast genome as control. The conversion rate for that sample is pretty good (here is the line in the log file generated by methylpy).
> The non-conversion rate is 0.33847922885%

**Comment by yupenghe** [comment]
great! Can you send me the methylpy output message of this sample? It has
the p-value cutoffs used to call methylated sites at the end.

**Comment by rbpisupati** [comment]
So the p-value cutoff (I assume it is for binomial test) is calculated for each context independently?

Btw, here is the [log file](https://github.com/yupenghe/methylpy/files/2137453/log.txt).

**Comment by yupenghe** [comment]
Yes

**Comment by yupenghe** [comment]
It is actually not an issue. With low non-conversion rate, 1 out of 1 can give you small p-value. I understand your concern about the coverage. In the latest version (1.3.3), you can use the `methylpy test-allc` function to redo the test with certain minimum coverage cutoff (--min-cov).

**Comment by rbpisupati** [comment]
Ok thanks..! I will test that it out.
