### ISSUE TITLE
SNP Calling Hints?

### ISSUE THREAD

**Issue by dakami** [yupenghe/methylpy#16]
Can you provide sample data for the SNP calling function?  I'd like to call all variants across all known SNPs and I'm not quite sure how.  Since the bisulfite process actually seems to work by corrupting one of the strands, I'm nervous about using "normal" WGBS-unaware tooling.

**Comment by yupenghe** [comment]
I would recommend to use [bissnp](http://people.csail.mit.edu/dnaase/bissnp2011/) instead. It is the tool developed to perform SNP calling using WGBS data.

**Comment by dakami** [comment]
I can do that, but bissnp takes bam files and I have fastq.  You do a ton of well-informed filtering.  At which stage should I grab your BAM, to feed into bissnp?

**Comment by yupenghe** [comment]
You can use the "singe-end-pipeline" or "paired-end-pipeline" for processing fastq files. If you set "--generate-allc-file" to false, methylpy will skip allc file generation and bam file (of reads that pass all filters) will be the final input. You can use the final bam file as input for bissnp.

**Comment by dakami** [comment]
I've got bam files, but they have no-clonal set.  Are they still valid inputs for bissnp?

Conveniently, you don't delete *that* bam file.

**Comment by yupenghe** [comment]
Yes. That should be a valid input for bissnp.

**Comment by dakami** [comment]
Perfect.  I wouldn't know if there were reasons the file would parse, but be semantically invalid in some weird way.  Thanks!
