### ISSUE TITLE
warning during DMRFind step

### ISSUE THREAD

**Issue by shahsam** [yupenghe/methylpy#18]
While running DMRFind module I get this warning:

`/home/x/miniconda3/envs/methylpy/lib/python3.6/site-packages/scipy/stats/stats.py:1713: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use 'arr[tuple(seq)]' instead of 'arr[seq]'. In the future this will be interpreted as an array index, 'arr[np.array(seq)]', which will result either in an error or a different result.
  return np.add.reduce(sorted[indexer] * weights, axis=axis) / sumval`

I am assuming this won't be a problem for my current analysis?

**Comment by yupenghe** [comment]
The analysis is very unlikely to be affected. Did you get any other warning or error?
