### ISSUE TITLE
DMR type is not consistent with methylation level

### ISSUE THREAD

**Issue by shahsam** [yupenghe/methylpy#20]
I ran methylpy for multiple samples, and then tried to reidentify DMRs in a subset of those samples. When I reidentify DMRs, I found some cases where the methylation levels do not correlate with the DMR labels. For instance, The methylation levels for a DMR in one sample is 0.78 and in the other is 0.68, but the latter is labeled as hypermethylated in the DMR reidentify results. What is the reason for this? I should note that compared to my remaining samples in the whole dataset, 0.68 is hypermethylated. But I don't understand why it still appears as hypermethylated when I am comparing it with just the 0.78 sample. 
Could you also elaborate on the min_cluster option? I read the documentation and it's still not clear to me. Thanks!
Here are the parameters I used for initial DMR finding and DMR reidentify steps:
```
methylpy DMRfind --allc-files <A B C D E F G H> --mc-type "CGN" --sig-cutoff 0.01
methylpy reidentify-DMR --input-rms-file rms_results.tsv.gz --sig-cutoff 0.01 --min-num-dms 5 --collapse-samples A B 
```

**Comment by yupenghe** [comment]
Hey, hypo/hyper calls are not only dependent on methylation level but also on the number of reads. What you described is totally possible if the 0.68 sample has a lot more reads covering CG sites within the DMR. It is also possible that within the DMR there are one or more CG sites in the 0.78 sample that showed conflicting methylation pattern (i.e. hypomethylation). The conflicts will disqualify that sample for being assigned as hyper. Pulling out the info of sites within DMR from `rms_results.tsv.gz` will help to identify what actually happened. 

`min_cluster` is used to filter out DMRs that are not consistently hyper/hypo- in at least one sample group (i.e. samples of one condition). A DMR will be filtered out if no category (sample group) has at least `min_cluster` number of samples in either hypo- or hyper- column. For example, 

```
sample sample_group
a g1
b g1
c g2
d g2
```

`min_cluster 2` means that for a DMR to pass filter, it need to either 1) have both `a` and `b` in hypo/hyper, 2) both `c` and `d` in hyper/hypo, or 3) both 1) and 2). Does it make sense?

`min_cluster` option is only useful when replicates are specified (i.e. replicate information is passed to methylpy through the `--sample-category` option).

**Comment by shahsam** [comment]
You are right Yupeng, I checked the rms file for this particular DMR (attached file) and the sample with 0.68 methylation level (LibB) has relatively more reads than the sample with 0.78 methylation level (LibA). Based on looking at tthese samples on a browser I think they also have a conflicting site, but I am not sure which columns in the rms results file indicate that. Thanks so much for explaining the details.
[rms_results_scaffold327_84685_84824.txt](https://github.com/yupenghe/methylpy/files/2704421/rms_results_scaffold327_84685_84824.txt)

**Comment by yupenghe** [comment]
Hi, It looks like the second samples show more sites that are hypermethylated. I am not sure about the p-value cutoff but we can just check the several most significant sites. The columns that determine hyper and hypo calls are `mc_residual_allc_LibA` and `mc_residual_allc_LibB`. For sites with smallest p-value 0.0003, second samples show very high residual (`mc_residual_allc_LibB) at `scaffold327:84685` and `scaffold327:84713`. When the sites are combined into DMRs, these two sites make the LibB called hypermethylated even though on average the methylation level of LibA is slightly higher than LibB. 

```chr     pos     strand  mc_class        pvalue  mc_allc_LibA    mc_allc_LibB    h_allc_LibA     h_allc_LibB     frac_allc_LibA  frac_allc_LibB  mc_residual_allc_LibA   mc_residual_\
allc_LibB   uc_residual_allc_LibA   uc_residual_allc_LibB   num_simulations_sig     num_simulations_run
scaffold327     84685   -       CGA     0.0003  4       10      6       12      0.6667  0.8333  2.1620  4.4900  -2.1620 -4.4900 1       3000
scaffold327     84696   +       CGC     0.0003  4       5       6       10      0.6667  0.5000  1.9997  1.4295  -1.9997 -1.4295 1       3000
scaffold327     84697   -       CGC     0.0003  4       8       6       12      0.6667  0.6667  2.2135  3.2103  -2.2135 -3.2103 1       3000
scaffold327     84712   +       CGA     0.0023  3       9       4       11      0.7500  0.8182  1.5108  3.1009  -1.5108 -3.1009 7       3000
scaffold327     84713   -       CGG     0.0003  3       9       4       11      0.7500  0.8182  1.9455  3.8420  -1.9455 -3.8420 1       3000
scaffold327     84791   +       CGT     0.0287  8       1       12      5       0.6667  0.2000  3.8005  -0.1756 -3.8005 0.1756  86      3000
scaffold327     84792   -       CGC     0.0010  4       9       6       14      0.6667  0.6429  2.3824  3.5635  -2.3824 -3.5635 3       3000
scaffold327     84794   +       CGG     0.1280  7       2       9       5       0.7778  0.4000  2.8494  0.2559  -2.8494 -0.2559 100     781
scaffold327     84795   -       CGA     0.0030  2       10      3       12      0.6667  0.8333  0.9269  3.1850  -0.9269 -3.1850 9       3000
scaffold327     84805   +       CGA     0.1712  9       1       9       2       1.0000  0.5000  2.9161  -0.1274 -2.9161 0.1274  100     584
scaffold327     84806   -       CGG     0.0040  3       7       3       11      1.0000  0.6364  1.5851  0.5974  -1.5851 -0.5974 12      3000
scaffold327     84823   +       CGC     0.2000  7       3       10      5       0.7000  0.6000  2.1816  1.0259  -2.1816 -1.0259 100     500
scaffold327     84824   -       CGC     0.0003  6       10      6       13      1.0000  0.7692  2.6125  2.2085  -2.6125 -2.2085 1       3000```
