### ISSUE TITLE
 methylpy single/paired-end-pipeline

### ISSUE THREAD

**Issue by Papareddy** [yupenghe/methylpy#23]
Hi ,

With methylpy paired or single end pipe line, if i havent missed, are there  any input options for methylpy to trim 5' base in extract with normal adaptor trimming to to mitigate Mbias.

Many Thanks,
Ranj

**Comment by yupenghe** [comment]
The feature is not available yet but you could manually trim the FASTQ and then feed the trimmed reads to methylpy for processing.
