### ISSUE TITLE
subprocess.CalledProcessError: Command '['wigToBigWig']

### ISSUE THREAD

**Issue by shengyongniu** [yupenghe/methylpy#25]
Hi, I have similar issue as #12 , but I can't solve it.
When I qsub a job for methylpy allc-to-bigwig with 1 or 10 CPU core and 10G memory, it sometimes shows the error and end the process:

Command:
`methylpy allc-to-bigwig --allc-file allc_hs_NeuN_neg.tsv --output-file allc_NeuN_neg_mCG_bin1.bw --ref-fasta hg19/genome/fasta/hg19.fa --mc-type CGN --bin-size 1`

`Traceback (most recent call last):
  File "anaconda3/envs/syniu/bin/methylpy", line 4, in <module>
    __import__('pkg_resources').run_script('methylpy==1.3.4', 'methylpy')
  File "anaconda3/envs/syniu/lib/python3.6/site-packages/pkg_resources/__init__.py", line 664, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "anaconda3/envs/syniu/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1444, in run_script
    exec(code, namespace, namespace)
  File "anaconda3/envs/syniu/lib/python3.6/site-packages/methylpy-1.3.4-py3.6.egg/EGG-INFO/scripts/methylpy", line 5, in <module>
    parse_args()
  File "anaconda3/envs/syniu/lib/python3.6/site-packages/methylpy-1.3.4-py3.6.egg/methylpy/parser.py", line 327, in parse_args
    add_chr_prefix=args.add_chr_prefix)
  File "anaconda3/envs/syniu/lib/python3.6/site-packages/methylpy-1.3.4-py3.6.egg/methylpy/utilities.py", line 252, in convert_allc_to_bigwig
    +output_file),stderr=subprocess.PIPE)
  File "anaconda3/envs/syniu/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['wigToBigWig', 'mCH_bin1.bw.wig', 'mCH_bin1.bw.chrom_size', 'mCH_bin1.bw']' returned non-zero exit status 1.`

First few line of chrom.size file
`chr1    249250621
chr2    243199373
chr3    198022430
chr4    191154276
chr5    180915260
chr6    171115067
chr7    159138663
chrX    155270560
chr8    146364022
chr9    141213431
chr10   135534747
chr11   135006516
chr12   133851895
chr13   115169878
chr14   107349540
chr15   102531392
chr16   90354753
chr17   81195210
chr18   78077248
chr20   63025520
chrY    59373566
chr19   59128983
chr22   51304566
chr21   48129895
`

few lines of wig file:
`chr1    11992   11993   0.1
chr1    11994   11995   0.0
chr1    11995   11996   0.0
chr1    11997   11998   0.0
chr1    12000   12001   0.15384615384615385
chr1    12003   12004   0.0
chr1    12005   12006   0.0
chr1    12006   12007   0.1
`

chromosome name in .fa file is like chr1

It works sometimes when I restart it, but sometimes it doesn't.  I can see the wigToBigWig help page when i use it in terminal. I also use around 10 CPU. Not sure if it's the subprocess issue.

Do you have any suggestion?

**Comment by yupenghe** [comment]
Is there an example that could be used to reproduce the error? It will be much easier to debug from there.

The error message indicates that it was the bash command methylpy tried to execute that failed. If you run the command directly: `wigToBigWig mCH_bin1.bw.wig mCH_bin1.bw.chrom_size mCH_bin1.bw`, what do you see?

**Comment by shengyongniu** [comment]
There is no problem when I just run the command wigToBigWig mCH_bin1.bw.wig mCH_bin1.bw.chrom_size mCH_bin1.bw. I install the wigtobigwig package from https://anaconda.org/bioconda/ucsc-wigtobigwig
Not sure if it's relative. Thanks!

**Comment by yupenghe** [comment]
Can you try the wigtobigwig from the link below?
http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64/
