### ISSUE TITLE
Crash during conversion into bigwig with "chr" when the chromosomes/contigs do not have the prefix chr

### ISSUE THREAD

**Issue by gverne** [yupenghe/methylpy#3]
https://github.com/yupenghe/methylpy/blob/5d43837f1976ef3699b3df3e4d0ad32d416c5c50/methylpy/utilities.py#L116

**Comment by yupenghe** [comment]
Thanks for reporting this issue. It should be fixed in the latest version.

**Comment by yupenghe** [comment]
Also, I added a parameter "--remove-chr-prefix" to control whether to remove "chr".

**Comment by gverne** [comment]
Yep saw that. Handy. Thanks!
