### ISSUE TITLE
Suggestion for downstream analysis.

### ISSUE THREAD

**Issue by CS791** [yupenghe/methylpy#30]
Hi! yupenghe,
I used methylpy which generated a bam file along with allc files. I need your suggestion regarding allc file contains all methylation context. I need to make separate files for CG, CHH, and CHG context and want to count (number as well in %) them individually. 
Is there any way I can pull out all the context individually and count them as there is no separate file generated given details of methylation statics. 

Thank you!
Best 

CS791

**Comment by yupenghe** [comment]
Hi CS791,
Allc file (after compression) is a giant table with each row corresponding to one cytosine. The detailed format is described here: https://github.com/yupenghe/methylpy#output-format

There is no built in code in methylpy to extract the the information you want. It requires some coding to do that unfortunately. Specifically, the table needs to be filtered by the fourth column to get the data of cytosines in CG, CHG and CHH context. Then, the methylation level can be calculated as the ratio of the sum of 5th column to the sum of 6th column.

**Comment by CS791** [comment]
Thank you yupenghe,
I will try something to extract the required context. I will let you once I am done.

Regards
CS791
