### ISSUE TITLE
Custom adapter

### ISSUE THREAD

**Issue by KaushikPanda1** [yupenghe/methylpy#31]
Hi,

There is a parameter for the adapter sequence as input, but unfortunately it is not working. If I use cutadapt to remove the adapters first and then input to methylpy, the mapping is much better. Any chance the adapter sequence is hardcoded into the program or am I running the program incorrectly. The following command did not successfully clip the adapters before mapping:

methylpy single-end-pipeline 
  --adapter-seq CTGTCTCTTATACACATCT 
  --read-files raw_reads/read.fastq.gz 
  --sample sampleName 
  --forward-ref index_methylpy_f 
  --reverse-ref index_methylpy_r 
  --ref-fasta template.fa 
  --num-procs 4 
  --unmethylated-control Control: 
  --binom-test TRUE 
  --min-cov 3 
  --remove-chr-prefix False 
  --pbat True 
  --compress-output FALSE 
  --path-to-output output/

Thanks for your help.

**Comment by yupenghe** [comment]
I will look into this issue. Do you mind to share a few reads for me to locate the problem? Thanks.

**Comment by KaushikPanda1** [comment]
Sure. I have attached 2 files. 1 file is adapter trimmed (using cutadapt) while the other is not. Untrimmed reads have an alignment rate of 6.83% to the positive strand, while trimmed reads have 44.96% alignment rate.

The command I used: 
methylpy single-end-pipeline --adapter-seq CTGTCTCTTATACACATCT --read-files test.fastq --sample test --forward-ref reference_methylpy_f --reverse-ref reference_methylpy_r --ref-fasta reference.fa --num-procs 4 --min-cov 3 --remove-chr-prefix False --pbat True --compress-output FALSE --path-to-output test_run1


[test_trimmed.fastq.zip](https://github.com/yupenghe/methylpy/files/3103700/test_trimmed.fastq.zip)
[test.fastq.zip](https://github.com/yupenghe/methylpy/files/3103701/test.fastq.zip)

**Comment by KaushikPanda1** [comment]
As I run this I realize, this might be a case of using pbat - True. If I try False, then I achieve the same alignment rate. But the adapters were added post bisulphite conversion and hence I chose the option pbat True. Can you please explain?

**Comment by yupenghe** [comment]
Thanks for the dataset and figuring this out. The key difference with/without pbat is that whether the read 1 comes from the same strand as the original fragment. In typical directional BS library, the read 1 is in the same strand as the original fragment and thus we don't need to run as pbat. In typical PBAT library, read 1 is on the opposite strand as the original fragment and methylpy has a pbat mode to deal with such case. I don't know the details of your library prep to tell but it should be related to this.
