### ISSUE TITLE
libgsl.so.0 cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by sherlock0088** [yupenghe/methylpy#35]
Hi Yupeng,
When I ran the DMRfind, I got such error information. 
![Annotation 2019-08-16 162357](https://user-images.githubusercontent.com/54190008/63197759-f4f7cd80-c078-11e9-9592-99134c2b11a2.png)
The code I used is:
methylpy DMRfind \
	--allc-files ./Allc/ICE2-CR-1.tsv.gz ./Allc/ICE2-CR-3.tsv.gz ./Allc/ICE2-HR-3.tsv.gz \
	--samples CR-1 HR-3 CR-3 \
	--mc-type "CGN" \
	--num-procs 8 \
	--output-prefix ICE
And I found that gsl-2.5 didn't generate the file named libgsl.so.0.  Only gsl-1.6 could generate libgsl.so.0. So could you adjust methlpy to fit both gsl 1.6 version and 2.5 verson?

**Comment by yupenghe** [comment]
Do you have `libgsl.so` file generated with gsl-2.5? If so,
`ln -s libgsl.so libgsl.so.0` should be able to fix the error.

**Comment by sherlock0088** [comment]
Yes, gsl-2.5 has libgsl.so. But I solved this problem by installing 1.6 version.
