### ISSUE TITLE
Destrand option for call-methylation-state ?

### ISSUE THREAD

**Issue by shellywanamaker** [yupenghe/methylpy#36]
Hi Yupeng! How are you?! I'm excited to be using methylpy for a BS-seq analysis on Geoduck clams. I already had Bismark .bam files, and wanted to use methylpy to call DMRs. Because our samples have low coverage, I am wondering if there is an option to "destrand" like there is in Methylkit as part of the unite function (https://bioconductor.org/packages/release/bioc/vignettes/methylKit/inst/doc/methylKit.html). Hope all is going well in CA!

**Comment by yupenghe** [comment]
Hey Shelly, things are going well. Unfortunately, there is no such option in methylpy. I have a perl script that can be used to pull out all CG position and merge the counts of symmetric ones (i.e. "destrand").

[destrand_cg.txt](https://github.com/yupenghe/methylpy/files/3537479/destrand_cg.txt)

**Comment by shellywanamaker** [comment]
awesome, thanks Yupeng!
