### ISSUE TITLE
--keep-temp-files not working

### ISSUE THREAD

**Issue by drfultz** [yupenghe/methylpy#38]
Hi,

I am attempting to perform the bowtie2 alignments within methylpy with reads allowed multiple mappings as in issue #19 .  However, the `--keep-temp-files True` option does not seem to be keeping any temporary files around.  I can see the initial .sam files being written during the run but then they are deleted by the end.  I am not getting any errors, indicating that methylpy recognizes the flag and its argument.

For reference, my full command is
`methylpy single-end-pipeline --read-files $READS --sample $NAME --forward-ref $FREF --reverse-ref $RREF --ref-fasta $FA_REF --num-procs 6 --keep-temp-files True --aligner-options \"-a\"`

I am using methylpy 1.3.8 installed via pip within a python 3.7 conda environment.

**Comment by yupenghe** [comment]
Just fixed it in 1.3.9. Please let me know if you still cannot get the .sam files with 1.3.9.

**Comment by drfultz** [comment]
Yes, we are now getting the temporary sam files for both strands.  However, again trying to replicate #19 , we are feeding these files (converted to sorted bam) into the call-methylation-state function.  The allc files that we get out of this have plenty of coverage at the proper mC sites, but are getting 0% methylation at every site (including sites that work in the standard pipeline).  We are using the unconverted genome as reference.  Are we doing something wrong?

`methylpy call-methylation-state --input-file $BAM --sample $NAME --ref-fasta $FA_REF --num-procs 6 --paired-end False --path-to-output $OUTPATH`

**Comment by yupenghe** [comment]
Do you mind to share some (~100) lines from the SAM file? The issue is likely due to the missing of a critical step before `call-methylation-state`. The reads are converted (C->T or G->A) and aligned to converted genome. The sequences of reads in the two SAM files are still converted and therefore, methylation level is 0%. We will need to counter-convert the bases on SAM and then run `call-methylation-state` to get the correct results.

**Comment by renganti** [comment]
Hello, I am writing on behalf of **drfultz**. We are both using the methylpy pipeline and ran into the same problem. I am attaching two text files. "out1.txt" is the first 100 lines of the SAM file but they are all unmapped reads so I am including another file "out2.txt" which has some mapped reads. The reads are indeed all converted as there are no C's in the sequence in the SAM file. Is there a function in methylpy that we can use to counter-convert the bases? Please let us know!

[out1.txt](https://github.com/yupenghe/methylpy/files/3682047/out1.txt)
[out2.txt](https://github.com/yupenghe/methylpy/files/3682048/out2.txt)

**Comment by yupenghe** [comment]
There is a script that could be used to reverse conversion.

[reverse_conversion.py.txt](https://github.com/yupenghe/methylpy/files/3684557/reverse_conversion.py.txt)

usage:
```python reverse_conversion.py --input-bam test.bam --output-bam test_output.bam```

**Comment by renganti** [comment]
Thank you very much! That script worked and I am seeing the differences in the methylation state now.
