### ISSUE TITLE
per site indicator of significant methylation is always 1

### ISSUE THREAD

**Issue by rbpisupati** [yupenghe/methylpy#4]
the allc file has all 1's even when the coverage is bad.
Ex. 
1	2	+	CCT	1	3	1
1	3	+	CTA	1	1	1
1	8	+	CCC	1	1	1
1	9	+	CCT	1	1	1
1	10	+	CTA	1	1	1
1	15	+	CCC	1	1	1
1	16	+	CCT	1	1	1
1	17	+	CTA	1	1	1
1	22	+	CCC	1	2	1
1	23	+	CCT	1	2	1
1	24	+	CTA	2	2	1
1	29	+	CCT	0	2	1
1	30	+	CTC	0	2	1
1	32	+	CTG	0	2	1

**Comment by yupenghe** [comment]
The last column is only useful when --binom-test is used (--unmethylated-control is also required to perform the test). By default, methylpy does not do the test to speed up processing and just places 1s in the last column of output allc file regardless of coverage.

**Comment by rbpisupati** [comment]
Can you add this to the README file of the repo? Also I think this should be done by default.

**Comment by yupenghe** [comment]
Thanks for the advice. I will add the information in README in the next update. 

I still prefer not to set it as default. The main reason is that 1) most analyses does not depend on this information. 2) Also, it requires to choose unmethylated control which is often not available (for example, many experiments do not have unmethylated lambda DNA spiked in and the sequence of an alternative, mitochondria/chloroplast, may not be in the reference genome). 3) This process takes extra computation. Therefore, it seems to me that "run as needed" is the better strategy.

**Comment by rbpisupati** [comment]
Ok agreed! But this has to be mentioned in the README or maybe put a NA in that column if the test is not run.

**Comment by yupenghe** [comment]
Thanks. It has been added to the README in the latest update.
