### ISSUE TITLE
--min-cluster parameter clarification

### ISSUE THREAD

**Issue by shellywanamaker** [yupenghe/methylpy#40]
Hi Yupeng!

I am looking for DMRs among 3 different categories with each category made up of 4 samples. I attempted to run DMRfind using the --min-cluster parameter set to 3 to require 3/4 samples per each category show coverage of the DMR. However, some DMRs returned had coverage of 3/4 samples from one category but only 1/4 samples from one other category and no coverage in any samples from the third category. For an example, see line 11 in the .txt (changed from .tsv for upload) results table created from the attached .sh.txt file. I interpreted category to mean treatment group. Am I misinterpreting what a category is or how this parameter should be used? Is there a away to require all groups or categories have coverage of a DMR in at least 3/4 samples per category?

Thanks,

Shelly

[day135_AllpH_DMR250bp_MCmax25_cov5x_clst3_rms_results_collapsed.txt](https://github.com/yupenghe/methylpy/files/3692935/day135_AllpH_DMR250bp_MCmax25_cov5x_clst3_rms_results_collapsed.txt)

[DMRfind3clstAllEPIsamples.sh.txt](https://github.com/yupenghe/methylpy/files/3692943/DMRfind3clstAllEPIsamples.sh.txt)

**Comment by yupenghe** [comment]
The description about this option could be a bit confusing. In the current implementation, it is the minimum number of samples in one category to present in the hyper/hypo-methylated group for a DMR to be valid. So, in your case, it is not what you want. There is no parameter for doing what you propose but you can do that by parsing the `rms_results_collapsed.tsv` file.

**Comment by shellywanamaker** [comment]
Got it. Thanks for clarifying @yupenghe!
