### ISSUE TITLE
DMRfind group statistics?

### ISSUE THREAD

**Issue by shellywanamaker** [yupenghe/methylpy#41]
Hi @yupenghe , happy Friday! I'm wondering if DMRfind calculates statistics to assess methylation differences between experimental groups ("sample-categories") or if it only calculates within-sample statistics. I'm wondering if I need to run an additional statistical test to identify group differences in % methylation from my rms_results_collapsed.tsv file.

**Comment by yupenghe** [comment]
Hi @shellytrigg, you will have to calculate the group-level statistics. Methylpy does not calculate group-wise difference but it is no super difficult to calculate statistics like difference in median/mean methylation level using R or python pandas. Let me know if it is still unclear.

Yupeng

**Comment by shellywanamaker** [comment]
Hi Yupeng,

Gotcha, it's clear. Thanks!

-Shelly

**Comment by shellywanamaker** [comment]
@yupenghe is there an easy way to get the mC and C count data that was used to get the percent methylation in the rms_results_collapsed.tsv? I'm currently filtering for coverage in the DMRfind command and employing the --mc-max-dist parameter, so I'm wondering which (if any) of the temp files contain this info. 

I'm looking for this info for running a binomial glm to assess group effect like was done [here](https://advances.sciencemag.org/content/4/6/eaar8028). I decided on that stat after looking at the distribution of percent methylation, which is naturally zero-inflated (and after arcsin(sqrt) transformation it's more normal but still zero- and one-inflated). Also, would love to know if you have any other suggestions for group stats on data like this. Thanks and happy Friday!

**Comment by yupenghe** [comment]
Hey @shellytrigg, you can get from the information from the `rms_results.tsv.gz` file which contains the coverage and mC count of each tested cytosine. The `mc_*` columns indicate the mC counts and the `h_*` columns are the coverage.

I am not sure about the question you try to answer but the method used in the referred paper is useful to associate differential methylation with various factors (e.g. experiment condition) conditioned on confounding factors (e.g. batches).

**Comment by shellywanamaker** [comment]
@yupenghe thanks for pointing me to the rms_results.tsv.gz file, that exactly what I was looking for. 

For the question I hope to answer, my data come from animals held under 4 different experimental conditions and I would like to know if methylation is affected by experimental condition. I think I will be able to get the glm to work with the data in the rms_results.tsv.gz file. Thanks!
