### ISSUE TITLE
problem loading picard

### ISSUE THREAD

**Issue by bigpocho** [yupenghe/methylpy#42]
hello im having this issue.

[bam_sort_core] merging from 0 files and 8 in-memory blocks...
Error: Unable to access jarfile picard/picard.jar
Traceback (most recent call last):
  File "/home/pocho/anaconda3/envs/BIT/bin/methylpy", line 5, in <module>
    parse_args()
  File "/home/pocho/anaconda3/envs/BIT/lib/python3.7/site-packages/methylpy/parser.py", line 185, in parse_args
    keep_temp_files=args.keep_temp_files)
  File "/home/pocho/anaconda3/envs/BIT/lib/python3.7/site-packages/methylpy/call_mc_pe.py", line 276, in run_methylation_pipeline_pe
    java_options=java_options)
  File "/home/pocho/anaconda3/envs/BIT/lib/python3.7/site-packages/methylpy/call_mc_se.py", line 1342, in remove_clonal_bam
    "QUIET=true"])
  File "/home/pocho/anaconda3/envs/BIT/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['java', '-Xmx20g', '-jar', 'picard/picard.jar', 'MarkDuplicates', 'INPUT=result_pend/p_end_libA_processed_reads.bam', 'OUTPUT=result_pend/p_end_libA_processed_reads_no_clonal.bam', 'ASSUME_SORTED=true', 'REMOVE_DUPLICATES=true', 'METRICS_FILE=result_pend/p_end_libA.metric', 'VALIDATION_STRINGENCY=LENIENT', 'QUIET=true']' returned non-zero exit status 1.

i have already added java path to enviroment variable  and have the path to picard.jar
any idea what could be going on ?

**Comment by bigpocho** [comment]
All test passed expect DMR, i havent installed all that dependencys yet

Test importing methylpy module.
- importing call_mc_se: pass
- importing call_mc_pe: pass
- importing DMRfind: pass
- importing parser: pass
Check methylpy executable:pass

methylpy is successfully installed!

Check whether dependencies are available in PATH
- find bowtie: failed
- find bowtie2: found version 2.3.5
- find minimap2: failed
- find samtools: found version 1.9
- find cutadapt: found version 1.18
- find java: found version 2019-07-16
Only bowtie2 is available. Skip tests for bowtie related code

Test DMRfind: failed
Test reidentify-DMR: failed

Test build-reference with bowtie2: pass

Test single-end-pipeline with bowtie2: pass

Test paired-end-pipeline with bowtie2: pass

Test quality filter for BAM file of single-end data: pass

Test call-methylation-state for single-end data: pass
Test call-methylation-state for paired-end data: pass

Test merge-allc: pass

Test filter-allc: pass

All tests are done!

**Comment by yupenghe** [comment]
Not sure if your problem is solved but you can try to provide the absolute path to your picard.jar.

**Comment by bigpocho** [comment]
Thank you for your response. Yeah it was solved. the problem was that the
picard.jar file was corrupted during the download it turn out that the
solution was to download it again.
