### ISSUE TITLE
DMRfind problem

### ISSUE THREAD

**Issue by olmath** [yupenghe/methylpy#43]
Hi Yupeng,
I am facing a problem with `methylpy DMRfind`.  Everything looks good when I run the `run_test.py` : 
```
Tue Nov 12 15:47:14 2019

Test importing methylpy module.
- importing call_mc_se: pass
- importing call_mc_pe: pass
- importing DMRfind: pass
- importing parser: pass
Check methylpy executable:pass

methylpy is successfully installed!

Check whether dependencies are available in PATH
- find bowtie: failed
- find bowtie2: found version 2.2.6
- find minimap2: found version 2.16-r922
- find samtools: found version 1.9
- find cutadapt: found version 2.6
- find java: found version 2019-03-19
Only bowtie2 is available. Skip tests for bowtie related code


Test DMRfind: pass
Test reidentify-DMR: pass

Test build-reference with bowtie2: pass
Test build-reference with minimap2: pass

Test single-end-pipeline with bowtie2: pass
Test single-end-pipeline with minimap2: pass

Test paired-end-pipeline with bowtie2: pass
Test paired-end-pipeline with minimap2: pass

Test quality filter for BAM file of single-end data: pass

Test call-methylation-state for single-end data: pass
Test call-methylation-state for paired-end data: pass

Test merge-allc: pass

Test filter-allc: pass

All tests are done!
```
However, when I try to use `DMRfind`on my data, I get the following: 
```
/Library/Python/2.7/site-packages/methylpy/utilities.py:14: UserWarning: Module argparse was already imported from /System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/argparse.pyc, but /Library/Python/2.7/site-packages is being added to sys.path
  from pkg_resources import parse_version
Filtering allc files using 2 node(s).
Tue Nov 12 15:44:40 2019

Splitting allc files for chromosome 1
Tue Nov 12 15:45:54 2019

(<type 'exceptions.KeyError'>, 184)
'1'
Running RMS tests failed.
```

May you please help me?

**Comment by yupenghe** [comment]
The information is not sufficient to determine the issue. Are you able to put together a small dataset to reproduce this error? 

If it is difficult, I can try to guess what was happening. It looks like that methylpy is trying to run DMRfind on the first chromosome `1` but this chromosome does not appear in the allc index file. Do you see the same error if you remove all the allc index file (*.idx) and rerun DMRfind?

**Comment by olmath** [comment]
Thank you Yupeng.
The chromosome label was the issue. I got `DMRfind`to run properly by changing the option `--chroms 1 2 3 4 5` for `--chroms Chr1 Chr2 Chr3 Chr4 Chr5` or by removing the option.
Just one note: I have noticed that in the `bed`files  generated by `DMRfind` another character string is added to the chromosome labels, for example:
````
chrChr1	928	929	CAG;-	0.0003
chrChr1	44690	44691	CAG;+	0.0003
chrChr1	587664	587665	CTG;+	0.0003
chrChr1	1249945	1249946	CCG;-	0.0003
chrChr1	1677042	1677043	CAG;+	0.0003`

**Comment by yupenghe** [comment]
It is due to a legacy problem: methylpy will add "chr" if the prefix is not "chr". It is confusing and I plan to remove this feature.
