### ISSUE TITLE
How are index files look like?

### ISSUE THREAD

**Issue by YibingZeng** [yupenghe/methylpy#44]
Is the index files are a set of files with the end of  .bt2 ???

**Comment by yupenghe** [comment]
It is something like this

```
1	0
2	3438
#eof
```

The first column is chromosome name and the second column marks the position in the file for accessing the cytosine methylation data of the corresponding chromosome.

**Comment by YibingZeng** [comment]
After building the index, I got lots of files with the end of .bt2. They are all binary files.
The command I used is:

```
methylpy build-reference --input-files Oh43.pseudomolecules-v1.fasta --output-prefix Oh43 --num-procs 8

```
Is that correct?

**Comment by yupenghe** [comment]
You are totally right. The `.bt2` are bowtie2 index file. I was confused because there are also other types of index files.

**Comment by YibingZeng** [comment]
But when I try to map the reads, it says:
 "/scratch/yz7799962/test/oh43/Oh43.pseudomolecules_index/Oh43_F" is not a Bowtie 2 index
Should I replace this folder as one of the following file:
Oh43_f.1.bt2
Oh43_f.2.bt2
Oh43_f.3.bt2
Oh43_f.4.bt2
Oh43_f.fasta
Oh43_f.rev.1.bt2
Oh43_f.rev.2.bt2

**Comment by yupenghe** [comment]
What was your command?
