### ISSUE TITLE
rms ValueError: could not convert string to float

### ISSUE THREAD

**Issue by shellywanamaker** [yupenghe/methylpy#45]
Hi Yupeng, happy friday!  

I am attempting to run DMRfind on some destranded bismark cytosine coverage files that I have reformatted to look like allc files. The files are located [here](https://gannet.fish.washington.edu/metacarcinus/Pgenerosa/analyses/20191220/). 

Here is an example of the first 10 lines of one file:

```
Scaffold_01	209		+	CGA	0	5	1
Scaffold_01	213		+	CGA	0	5	1
Scaffold_01	221		+	CGA	0	6	1
Scaffold_01	238		+	CGA	0	8	1
Scaffold_01	565		+	CGA	0	6	1
Scaffold_01	577		+	CGA	0	6	1
Scaffold_01	583		+	CGA	0	5	1
Scaffold_01	2509	+	CGA	0	7	1
Scaffold_01	2554	+	CGA	0	6	1
Scaffold_01	3002	+	CGA	0	5	1
```

Because these are destranded I have included "+" for each cytosine loci and since the context was not included in the original file, I added "CGA" for each cytosine loci.

When I run DMRfind on these files, I get a weird error: 

```
gsl: discrete.c:238: ERROR: probabilities must be non-negative
Default GSL error handler invoked.
gsl: discrete.c:238: ERROR: probabilities must be non-negative
Default GSL error handler invoked.
gsl: discrete.c:238: ERROR: probabilities must be non-negative
Default GSL error handler invoked.
Traceback (most recent call last):
  File "/Users/strigg/anaconda3/bin/methylpy", line 5, in <module>
    parse_args()
  File "/Users/strigg/anaconda3/lib/python3.6/site-packages/methylpy/parser.py", line 71, in parse_args
    seed=args.seed)
  File "/Users/strigg/anaconda3/lib/python3.6/site-packages/methylpy/DMRfind.py", line 274, in DMRfind
    convergence_diff=convergence_diff)
  File "/Users/strigg/anaconda3/lib/python3.6/site-packages/methylpy/DMRfind.py", line 319, in merge_DMS_to_DMR
    input_rms_file)
  File "/Users/strigg/anaconda3/lib/python3.6/site-packages/methylpy/DMRfind.py", line 482, in get_resid_cutoff
    residuals.append(float(resid))
ValueError: could not convert string to float: '-0.0Scaffold_01'
```
It seems like there is some strange formatting happening in the rms_results.tsv.gz file that causes the script to break and not produce the collapsed.tsv file. 

I tried updating methylpy and gsl (and recompiling), but still got the same error. I ran the run_test.py script and everything passed, so I feel like it's probably my files. Here's my [jupyter notebook](https://github.com/shellytrigg/Shelly_Pgenerosa/blob/master/analyses/20191220_DMRfind_5xmerg.ipynb) documenting all this.

I also tried running this from another computer that methylpy has worked on and I get the same error (see my output logs [here](https://gannet.fish.washington.edu/metacarcinus/Pgenerosa/analyses/20191220/slurm-1584223.out) and [here](https://gannet.fish.washington.edu/metacarcinus/Pgenerosa/analyses/20191220/slurm-1584227.out)

Have you seen this behavior before? Any advice for moving forward? Thanks!

**Comment by yupenghe** [comment]
Hey Shelly, I think it is likely caused by issue in formatting. In allc format, the 6th column is the number of total coverage whereas the 5th column is number of reads supporting methylation. Therefore, 5th column should always be smaller than 6th column. This is violated in some of the rows in the files you shared. I would suggest checking the generation of allc files.

**Comment by shellywanamaker** [comment]
Hi Yupeng, thanks for catching this error. It turns out that column with # unmethylated Cs instead to total Cs. I have corrected the files and was able to run DMRfind successfully. Thanks!
