### ISSUE TITLE
DMRfinnd RMS issue

### ISSUE THREAD

**Issue by Papareddy** [yupenghe/methylpy#49]
Hi Yunpenghe,

I hope alls well with you.

I have a problem running DMRfind. which is giving me the below error. I think its not a file formate problem as I have been used the software well before and it might not be a dependencies problem because I run independently on the cluster and in anaconda environment and giving me the same error.

Could you please gimme a hit what might be happening.

Many Thanks,
Ranj 

[ranjith.papareddy@clip-c2-2 Main_Cot_stem_aligned_bams]$ methylpy DMRfind  --output-prefix CotvsStem.CHH --mc-type 'CHH'  --min-cov 4 --num-sims 1000 --min-num-dms 4  --samples allc_LowerStem_F1_trimmed_bismark_bt2.Chsort  allc_Cotyledon_C1_trimmed_bismark_bt2.Chsort  --allc-files ../../methylation_man/Dev.series.DMRs/BC.WT.tsv ../../methylation_man/Dev.series.DMRs/Heart.WT.tsv
Filtering allc files using single node.
Wed Feb  5 14:30:52 2020

Splitting allc files for chromosome chloroplast
Wed Feb  5 14:32:24 2020

Running rms tests for chromosome chloroplast
Wed Feb  5 14:32:25 2020

/software/2020/software/methylpy/1.2.9-foss-2018b-python-2.7.15/lib/python2.7/site-packages/methylpy-1.2.9-py2.7.egg/methylpy/run_rms_tests.out: error while loading shared libraries: libgsl.so.0: cannot open shared object file: No such file or directory
(<class 'subprocess.CalledProcessError'>, 204)
Command '['/software/2020/software/methylpy/1.2.9-foss-2018b-python-2.7.15/lib/python2.7/site-packages/methylpy-1.2.9-py2.7.egg/methylpy/run_rms_tests.out', 'CotvsStem.CHH_filtered_allc_allc_LowerStem_F1_trimmed_bismark_bt2.Chsort.tsv_chloroplast_0.tsv,CotvsStem.CHH_filtered_allc_allc_Cotyledon_C1_trimmed_bismark_bt2.Chsort.tsv_chloroplast_0.tsv', 'CotvsStem.CHH_rms_results_for_chloroplast_chunk_0.tsv', 'allc_LowerStem_F1_trimmed_bismark_bt2.Chsort,allc_Cotyledon_C1_trimmed_bismark_bt2.Chsort', '4', '1000', '100', '-1']' returned non-zero exit status 127
Running RMS tests failed.

[ranjith.papareddy@clip-c2-2 Main_Cot_stem_aligned_bams]$ tail ../../methylation_man/Dev.series.DMRs/BC.WT.tsv
4	18585035	-	CCT	18	20	1
4	18585036	-	CCC	17	18	1
4	18585041	-	CTA	15	15	1
4	18585042	-	CCT	13	13	1
4	18585043	-	CCC	10	10	1
4	18585048	-	CTA	7	7	1
4	18585049	-	CCT	7	7	1
4	18585050	-	CCC	6	6	1
4	18585055	-	CTA	1	1	1
4	18585056	-	CCT	1	1	1
[ranjith.papareddy@clip-c2-2 Main_Cot_stem_aligned_bams]$

**Comment by yupenghe** [comment]
It looks like an issue with the installation of GSL library. You can see here: https://github.com/yupenghe/methylpy#optional-step---compile-rmscpp

You can also run methylpy without installing GSL if you have access to docker. 
See https://github.com/yupenghe/methylpy#use-methylpy-without-installation

**Comment by Papareddy** [comment]
Thank you very much. I will try with docker and see : )
