### ISSUE TITLE
DMRfind error during merging DMS to DMR

### ISSUE THREAD

**Issue by shahsam** [yupenghe/methylpy#50]
Dear Yupeng, 
I am having trouble with running DMRfind for some of my datasets that were downloaded from NCBI (Arabidopsis bisulfite seq GSE67216). I used methylpy to generate the allC files and then merge replicates for samples -all of which worked fine. When I run DMRfind, I get an error during residual cutoff stage (see below), and the final DMS/DMR files are not generated. Could you help me to figure out how to fix this?
```
Calculating Residual Cutoff
Tue Feb 18 11:16:32 2020

Traceback (most recent call last):
  File "/home/s/miniconda3/bin/methylpy", line 5, in <module>
    parse_args()
  File "/home/s/miniconda3/lib/python3.7/site-packages/methylpy/parser.py", line 71, in parse_args
    seed=args.seed)
  File "/home/s/miniconda3/lib/python3.7/site-packages/methylpy/DMRfind.py", line 274, in DMRfind
    convergence_diff=convergence_diff)
  File "/home/s/miniconda3/lib/python3.7/site-packages/methylpy/DMRfind.py", line 319, in merge_DMS_to_DMR
    input_rms_file)
  File "/home/s/miniconda3/lib/python3.7/site-packages/methylpy/DMRfind.py", line 482, in get_resid_cutoff
    residuals.append(float(resid))
ValueError: could not convert string to float: '-'
```
Here is the code I used for DMRfind
```
methylpy DMRfind --allc-files methylpy_results/merged_allc/allc_merged_A.tsv.gz methylpy_results/merged_allc/allc_merged_B.tsv.gz methylpy_results/merged_allc/allc_merged_C.tsv.gz --mc-type "CHH" --num-procs 8 --min-cov 3 --output-prefix repeat_dmrs/CHH_sig01_dms0_cov3
```
I have used the same code for other files and it works fine. The merged allC files don't seem to have any issue. Here are the first few lines from one of the allC files:
```
$gunzip -d -c allc_merged_A.tsv.gz |tail
3	23459756	+	CAC	1	4	1
3	23459758	+	CCT	1	4	1
3	23459759	+	CTT	0	4	1
3	23459762	+	CGA	0	3	1
3	23459763	-	CGA	0	1	1
3	23459765	+	CAC	0	3	1
3	23459767	+	CCA	0	3	1
3	23459768	+	CAG	0	2	1
3	23459770	-	CTG	0	1	1
3	23459771	+	CCT	0	1	1
$ gunzip -d -c allc_merged_A.tsv.gz |cut -f1|sort|uniq -c
10272463 1
6721681 2
8173516 3
6428501 4
9248527 5
  42315 chloroplast
  62756 mitochondria
```
Below are the codes to generate the allC files:
```
methylpy single-end-pipeline \
	 --read-files SRR1927188_GSM1642569.fastq.gz  \
	 --sample rep1_SRR1927188 \
	 --trim-reads True \
	 --unmethylated-control chloroplast: \
	 --forward-ref TAIR10_chr_all.fas.shIDs_f \
	 --reverse-ref TAIR10_chr_all.fas.shIDs_r \
	 --ref-fasta TAIR10_chr_all.fas.shIDs.fa \
	 --num-procs 8 \
	 --compress-output False \
	 --path-to-output methylpy_results/

methylpy merge-allc \
	 --allc-files methylpy_results/allc_rep1_SRR1927188.tsv methylpy_results/allc_rep2_SRR1927189.tsv methylpy_results/allc_rep3_SRR1927190.tsv \
	 --output-file methylpy_results/merged_allc/allc_merged_C.tsv.gz \
	 --compress-output True
```

**Comment by yupenghe** [comment]
Do you mind to share some files for me to reproduce the error?

**Comment by shahsam** [comment]
Please see the following link for a zip file with the three merged allC files that I used for DMRfind run: 
https://www.dropbox.com/s/l0rnq73rx54rqx8/merged_allc.tar.gz?dl=0
Let me know if you need any other files. Thanks!

**Comment by yupenghe** [comment]
Thanks. I ran DMRfind on your allc files and I was not able to reproduce the error. One possibility is that this is a random error. If you rerun your command, would you see the same error? 

Here is the output files I got in case you want to take a look: http://neomorph.salk.edu/yupeng/share/chh_dmr.tar
Please let me know when it is ok for me to delete it.

**Comment by shahsam** [comment]
Hi Yupeng, you can delete the output file. I have run these files twice in my machine, but both times it failed with some random parsing error at the DMS merging stage. First, time I thought it was a random error, but I got another slightly different parsing error the second time. It might be some issue specific to my machine environment. I am going to try to run these on a different machine and see if everything works well. Thanks for your help :)

**Comment by shahsam** [comment]
Hey Yupeng, I tried in a different machine and everything worked alright! I think the error was specific to some memory-related issues in my original machine which only affected this particular dataset. Thanks again for checking this for me!
