### ISSUE TITLE
input files for add-methylation-level

### ISSUE THREAD

**Issue by WWJiaxuan** [yupenghe/methylpy#51]
Hi Yupeng,

Hope this finds you well!

I am now trying to use methylpy to summarize data into gene level by function "add-methylation-level". In other words, to generate a gene by cell matrix. However, I encountered a small problem, could you please be so kind as to do me a favor looking at it?

I inputted gene information to be the "input-tsv-file". For the input allc file, raw data is not available, so I am afraid single/paired-end-pipeline can not applied to generate allc file. What I could get is just 4 columns (i.e. chromosome, position, number of methylated reads and number of total reads). The remaining 3 columns (strand, sequence context, methylated) were missing in my case. Is it possible to run the "add-methylation-level" to get a gene by cell matrix?

Just for your information, I actually have used these 4 columns to run "add-methylation-level", but it turned out all the entries were "NA". I am quite confused about the result, and I guess it is because of the allc file. 

Thanks in advance for your time! Looking forward to hear from you.

**Comment by yupenghe** [comment]
Hi, it is possible to run methylpy with the 3 columns missing but they need to be filled with appropriate values. I would suggest "+" for strand, "CGN" for sequence context and "1" for methylated. Please let me know if it works.

Yupeng

**Comment by WWJiaxuan** [comment]
Hi, Yupeng, thanks very much for your quick reply and your suggestion. 

Yes, it works! I am just wondering if it is reasonable to have more than 95% ( 225901/27751) "NA" in the output? 

I also got another little question. I compress all the cell allc files into only ONE .tgz files, is it possible for "add-methylation-level" to take .tgz (compressed file) and recognize it as several allc input files? Since I have tried one .tgz file, it seemed that the program never ends.

Thanks again!

**Comment by yupenghe** [comment]
You may want to check whether the tsv file is sorted by coordinates. Otherwise, the values you got are probably not correct. 

Thanks for the suggestion but taking a tar ball as input is not supported by methylpy yet.

Yupeng

**Comment by WWJiaxuan** [comment]
Hi, Yupeng, thank you for your reply.

May I know further what "tsv file is sorted by corordinates" means? Does it mean for every chromosome, I need to sort the positions from least number to largest number?

Thanks in advance!

**Comment by yupenghe** [comment]
Exactly. You can use the below command to do that.

```head -n 1 TSV_FILE > header
tail -n +2 TSV_FILE|sort -k 1,1 -k 2,2g -k 3,3g |cat header - > TSV_FILE_REFORMATTED
rm header
```

**Comment by WWJiaxuan** [comment]
Hi, Yupeng, thank you for the further suggestion, and it really helps! After sorting the coordinates, the results become more reasonable.

Thanks again for your time and valuable advice!

**Comment by WWJiaxuan** [comment]
Hi, Yupeng. Sorry to bother you again.

Now I am running "add-methylation_level" for 52 samples, and I got an error message as below.

> rm: cannot remove ‘March15_HSC_methy_gene_level_cmp_0_D2_1_R2_allc_reformed_temp_methylation_levels.tsv’: No such file or directory
Traceback (most recent call last):
  File "/home/wangwujiaxuan/.local/bin/methylpy", line 5, in <module>
    parse_args()
  File "/home/wangwujiaxuan/.local/lib/python2.7/site-packages/methylpy/parser.py", line 270, in parse_args
    input_no_header=args.input_no_header)
  File "/home/wangwujiaxuan/.local/lib/python2.7/site-packages/methylpy/DMRfind.py", line 888, in get_methylation_levels_DMRfind
    subprocess.check_call(shlex.split("rm "+output.replace(".tsv","")+"_"+sample+"_temp_methylation_levels.tsv"))
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['rm', 'March15_HSC_methy_gene_level_cmp_0_D2_1_R2_allc_reformed_temp_methylation_levels.tsv']' returned non-zero exit status 1

FYI, 'March15_HSC_methy_gene_level_cmp.tsv' is my output file name, and 'CMP_50_D2_1_R2_allc_reformed.tsv' is my input allc filename. 

Since I have 'CMP_50_D2_1_R2_allc_reformed.tsv' and 'CMP_10_D2_1_R2_allc_reformed.tsc', according to the output name, these two will share the same name "March15_HSC_methy_gene_level_cmp_0_D2_1_R2_allc_reformed_temp_methylation_levels.tsv". Is this the reason which causes the error? If it is, is it possible to output full allc filename to avoid this kind of confusion? If it is not, may I know is there any way to deal with it?

Thank in advance! Looking forward to your reply!

**Comment by yupenghe** [comment]
Hi, the naming of allc files look like the cause. I would recommend changing the names of the allc files such that they have different basename (e.g. "CMP_50_D2_1_R2_allc_reformed_1" and "CMP_50_D2_1_R2_allc_reformed_2") and the same suffix ".tsv". 

Yupeng

**Comment by WWJiaxuan** [comment]
Hi, Yupeng. 

Sure, I have already changed the name. Thanks again for your continuous help!
