### ISSUE TITLE
why are some regions with >= min_num_dms not called DMRs?

### ISSUE THREAD

**Issue by shellywanamaker** [yupenghe/methylpy#52]
Hi @yupenghe ! In looking through DMRs and DMS in IGV, I'm finding some regions that look like they should be called DMRs, but there were not (see screenshot example). In the screenshot, the top 4 samples are one treatment group (orange), the next 4 are one treatment group (blue), and the last 4 are one treatment group (red). 
![Screen Shot 2020-03-17 at 10 29 15 AM](https://user-images.githubusercontent.com/4720221/76887438-8877c380-683f-11ea-8bdf-5c01d8574d70.png)

To me, this is showing that generally the blue and orange groups are not methylated at these DMS while the red group is. Why would DMRfind not classify these DMS as a DMR? 

- DMRfind code below was executed in this [jupyter notebook](https://github.com/shellytrigg/Shelly_Pgenerosa/blob/master/analyses/20191222_DMRfind_5xmerg.ipynb): 
```
methylpy DMRfind \
--allc-files EPI-103_S27_L005_5xmerg_allc.tsv \
EPI-104_S28_L005_5xmerg_allc.tsv \
EPI-111_S29_L005_5xmerg_allc.tsv \
EPI-113_S30_L005_5xmerg_allc.tsv \
EPI-119_S31_L005_5xmerg_allc.tsv \
EPI-120_S32_L005_5xmerg_allc.tsv \
EPI-135_S35_L005_5xmerg_allc.tsv \
EPI-136_S36_L005_5xmerg_allc.tsv \
EPI-127_S33_L005_5xmerg_allc.tsv \
EPI-128_S34_L005_5xmerg_allc.tsv \
EPI-143_S37_L005_5xmerg_allc.tsv \
EPI-145_S38_L005_5xmerg_allc.tsv \
--samples EPI-103 EPI-104 EPI-111 EPI-113 EPI-119 EPI-120 EPI-135 EPI-136 EPI-127 EPI-128 EPI-143 EPI-145 \
--mc-type "CGN" \
--num-procs 8 \
--output-prefix day10_AllpH_DMR250bp_MCmax25_cov5x \
--mc-max-dist 25 \
--dmr-max-dist 250 \
--min-num-dms 3 \
--sample-category 0 0 1 1 2 2 2 2 0 0 1 1
```
- Output:
	- [rms_results.tsv.gz](https://gannet.fish.washington.edu/metacarcinus/Pgenerosa/analyses/20191222/day10_AllpH_DMR250bp_MCmax25_cov5x_rms_results.tsv.gz)
	- [rms_results_collapsed.tsv](https://gannet.fish.washington.edu/metacarcinus/Pgenerosa/analyses/20191222/day10_AllpH_DMR250bp_MCmax25_cov5x_rms_results_collapsed.tsv)
	- [DMR.bed](https://gannet.fish.washington.edu/metacarcinus/Pgenerosa/analyses/20191222/day10_AllpH_DMR250bp_MCmax25_cov5x_rms_results_collapsed.tsv.DMR.bed)
	- [DMS.bed](https://gannet.fish.washington.edu/metacarcinus/Pgenerosa/analyses/20191222/day10_AllpH_DMR250bp_MCmax25_cov5x_rms_results_collapsed.tsv.DMS.bed) 
	- [.bw files](https://gannet.fish.washington.edu/metacarcinus/Pgenerosa/analyses/20200311/) were generated by [this code](https://github.com/shellytrigg/Shelly_Pgenerosa/blob/master/analyses/20200312_allc2bw_destranded.ipynb)
	- [IGV session](https://github.com/shellytrigg/Shelly_Pgenerosa/blob/master/analyses/20200311_compare_DMRfind_output/20200311_D10Samples_noMCmax_vs_MCmax25.xml)

**Comment by yupenghe** [comment]
Hey Shelly, hope everything is going well. I looked over this case. In your command, the sample category is set and by default DMSs are grouped into DMRs only when there are at least 2 samples from one sample category that are either classified as hypo- or hyper-. The issue of these 4 DMSs is that methylpy consider them to hypomethylated only in EPI-113 sample. Thus, they were skipped. 

There is a parameter `--min-cluster` where the cutoff can be set. Using `--min-cluster 1` should solve this problem. 

Yupeng

**Comment by shellywanamaker** [comment]
@yupenghe doing ok so far. Austin and I are both working remotely staying hunkered down here in Seattle. How are things in the Bay area?

That makes sense why the command didn't call the DMR if it requires at least 2 samples from one category to be classified as hypo- or hyper-methylated. I will try your --min-cluster 1 suggestion.

I'm still wondering how does the command handle DMS that have no methylation? I think what's interesting here is the red group is in general hyper-methylated, where the blue and orange groups are not methylated or hypo-methylated. What if, for instance, these DMS had no methylation in the blue and orange group and hypermethylation in the red group. Would that still be captured using the --min-cluster 1 setting?

Thanks @yupenghe  and hope all is well for you!

**Comment by yupenghe** [comment]
Thanks. Things are fine. I am also working from home and have been at home for weeks :)

The --min-cluster is equally applied to all sample groups and it is equally applied to both hypomethylation and hypermethylation cases. The issue of the above 4 DMSs is that only EPI-113 is called as hypo- and no samples are called as hyper-. In the cases where fore example EPI-113 is hyper- and no samples are hypo- in a few adjacent DMSs, setting `--min-cluster 1` will also let you collapse DMSs into DMR. Hope it makes sense.

Yupeng

**Comment by shellywanamaker** [comment]
Hi Yupeng,

That does make sense. Thanks for clarifying everything!

-Shelly
