### ISSUE TITLE
default DMRfind --dmr_max_dist 

### ISSUE THREAD

**Issue by shellywanamaker** [yupenghe/methylpy#55]
Hi Yupeng! Is there rationale behind the default DMRfind --dmr_max_dist being 250bp?

**Comment by yupenghe** [comment]
`--dmr-max-dist` specifies the maximum distance to merge DMSs that have similar methylation pattern. 250bp is arbitrary to some degree but it can be justified by the observation that the methylation status of CpGs within ~200bp are correlated. 

Another way to look at it is the minimum distance between two DMRs.

**Comment by shellywanamaker** [comment]
@yupenghe cool, thanks for the explanation!
