### ISSUE TITLE
DMRfind with multiple repeats

### ISSUE THREAD

**Issue by coralzhang** [yupenghe/methylpy#56]
Hi, 

I am using the DMRfind on two groups (say A and B) each with multiple repeats, thus I am intereseted in finding the DMR that is different between groups, and not interested in any DMR that is within group. I wonder how should I reflect this?

Thanks!

**Comment by yupenghe** [comment]
You can use the `--sample-category` option to specify the sample group

The option is described in https://github.com/yupenghe/methylpy/blob/methylpy/tutorial/tutorial.md#dmr-calling

**Comment by coralzhang** [comment]
Thank you very much!

**Comment by coralzhang** [comment]
I just notice that the "rms_results_recollapsed.tsv" from "reidentify-DMR" does not have the methylation levels attached. Is this normal?

**Comment by yupenghe** [comment]
That is expected. `add-methylation-level` is needed to get the methylation levels.

**Comment by coralzhang** [comment]
I see. Thank you so much for your patient answers.
