### ISSUE TITLE
add-methylation-level issue

### ISSUE THREAD

**Issue by WWJiaxuan** [yupenghe/methylpy#57]
Hi yupeng,

Hope you are well.

I am sorry to bother you. I just encounter a problem when trying to use add-methylation-level to aggregate data. My data file and genomic file have different chromosomes. For example, there're chromosome 1  10 11 12 13 14 15 16 17 18 19 2  3  4  5  6  7  8  9  X  Y in my genomic file, while only 1  10 11 12 13 14 15 16 17 18 19 2  3  4  5  6  7  8  9  X in my data file, so it gives error. May I know is there anything I can do to handle it? (Like automatically fill NA in entries of Y) Do I need to modify my data file? If so, could you please give me some advise on it?

Thanks in advance and looking forward to your reply!

**Comment by yupenghe** [comment]
Hey, can you send me the error you got?

**Comment by WWJiaxuan** [comment]
Hi yupeng,

Thanks for you reply. I am sorry that I missed your reply before. Here's the error message.

`Traceback (most recent call last):
  
File "/home/wangwujiaxuan/.local/bin/methylpy", line 5, in <module>
    
parse_args()
  
File "/home/wangwujiaxuan/.local/lib/python2.7/site-packages/methylpy/parser.py", line 270, in 

parse_args
    
input_no_header=args.input_no_header)
  
File "/home/wangwujiaxuan/.local/lib/python2.7/site-packages/methylpy/DMRfind.py", line 854, in get_methylation_levels_DMRfind
    
input_no_header)
  
File "/home/wangwujiaxuan/.local/lib/python2.7/site-packages/methylpy/DMRfind.py", line 925, in get_methylation_level_DMRfind_worker
    
allc_file.seek(chrom_pointer[dmr_chr])

KeyError: 'Y'
`
FYI, my sample file does not contain chromosome Y, but the genomic file has chromosome Y. That's why the error pops up.

**Comment by yupenghe** [comment]
Thanks. The easiest solution is to remove the regions from chromosome Y in your genome file. Please let me know if you need help with that.

**Comment by WWJiaxuan** [comment]
Thanks for your suggestion!

Sure, may I know is there any easy way to remove chromosome Y region? Now I need to delete all regions and sort the coordinates again.

Since I might still need to keep chromosome Y in the later analysis, so I am just wondering if methylpy can automatically deal with it (like fill NA in the chr Y region)?

**Comment by yupenghe** [comment]
I updated the code to support this. Can you please check whether the issue is resolved after updating methylpy?

**Comment by WWJiaxuan** [comment]
Hi yupeng,

I just tried the updated code, and it worked pretty well. Thanks very much for your effort and time! It really helped me a lot.

Thanks again and take care!
