### ISSUE TITLE
DMRfind Running RMS tests failed.

### ISSUE THREAD

**Issue by BTSARMY0613** [yupenghe/methylpy#59]
Hi Yunpenghe,

I have a problem running DMRfind, and the error is "Running RMS tests failed." I used to think it's because  of my gsl wasn't installed properly. But I really have installed GSL according to the installation tutorial, and when I excute run_rms_tests.out it showed "Usage: ./rms.out <chunk files> <output file> <samples> <min_cov> <num_sims> <num_sig_tests> <seed>".Now I can't use docker and I have no idea about this "Running RMS tests failed" error, could you please help me what causes this error and how to solve this problem? The code I run is as follow.

methylpy DMRfind --allc-files /share/data/Methylpy/g1/g1_allc.txt  /share/data/Methylpy/g2/g2_allc.txt --sample-category g1 g2 --min-cluster 2 --mc-type CGN --chroms 1 --num-procs 2 --keep-temp-files FALSE --output-prefix /share/data/Methylpy/result/g1_g2

Many Thanks,
Sope

**Comment by yupenghe** [comment]
Hey Sope,
Do you mind to share some input files for me to reproduce the error?

Yupeng

**Comment by BTSARMY0613** [comment]
Thank you yupenghe,

The following two files are my input files. The category of allc_GSM2481635.txt is g2, and the category of allc_GSM2481637.txt is g1. I can run after deleting the chromosome label item, like this,
methylpy DMRfind --allc-files /Methylpy/g1/allc_GSM2481637.txt  /Methylpy/g2/allc_GSM2481635.txt --sample-category g1 g2 --min-cluster 2 --mc-type CGN --num-procs 2 --keep-temp-files FALSE --output-prefix /Methylpy/result2/g1_g2

[allc_GSM2481635.txt](https://github.com/yupenghe/methylpy/files/5089378/allc_GSM2481635.txt)
[allc_GSM2481637.txt](https://github.com/yupenghe/methylpy/files/5089379/allc_GSM2481637.txt)

But the result does not seem to be right. The result file's image is as follows. Is there a problem with the format of my input file or is my dependency not installed? I did not install bowtie, samtools, Picard, wigToBigWig, but I just want to get DMR information.
![image](https://user-images.githubusercontent.com/49978834/90494133-c02fc200-e175-11ea-9e26-f12d4e1d8a1b.png)

Many Thanks!
Sope

**Comment by BTSARMY0613** [comment]
Oh, I almost forgot, and this picture is the output after I run it
![image](https://user-images.githubusercontent.com/49978834/90495344-15200800-e177-11ea-9f16-efff941b7a6b.png)

**Comment by yupenghe** [comment]
Hi Sope,
The error was due to the format of allc file. It needs to be tab separated. If you use R, you can reformat the file as
```
allc = read.table("allc_GSM2481635.txt")
write.table(x=allc, file="allc_GSM2481635.tsv", sep="\t", quote=F, col.names=F, row.names=F)

allc = read.table("allc_GSM2481637.txt")
write.table(x=allc, file="allc_GSM2481637.tsv", sep="\t", quote=F, col.names=F, row.names=F)
```

Then, DMRfind can be run using command like this
```
methylpy DMRfind --allc-files allc_GSM2481637.tsv allc_GSM2481635.tsv --sample-category g1 g2 --min-cluster 2 --mc-type CGN --num-procs 2 --keep-temp-files FALSE --output-prefix g1_g2
```

**Comment by BTSARMY0613** [comment]
Oh thank you! Many thanks! You help me a lot!
