### ISSUE TITLE
DMR results are empty

### ISSUE THREAD

**Issue by rbpisupati** [yupenghe/methylpy#6]
Hi, 

I was trying to identify the DMRs using methylpy. But the results file is empty with just header. 
The command and its output are here. 

```
>methylpy DMRfind --allc-files allc_temp17.tsv.gz allc_temp18.tsv.gz allc_temp19.tsv.gz allc_temp20.tsv.gz --samples temp17 temp18 temp19 temp20 --mc-type CG --num-procs 8 --output-prefix run4

Splitting allc files for chromosome Chr1
Thu Dec 28 13:04:39 2017

Running rms tests for chromosome Chr1
Thu Dec 28 13:04:39 2017

Merging sorted run4_rms_results.tsv files.
Thu Dec 28 13:04:39 2017

Begin FDR Correction
Thu Dec 28 13:04:39 2017

m0 estimate for iteration 0: 0
Histogram FDR correction did not converge. Using the smallest p-value 0.000333333333333 as cutoff.

Calculating Residual Cutoff
Thu Dec 28 13:04:39 2017

There are no null residuals to calculate resid_cutoff. Using 2 as the cutoff.
Begin Defining Windows
Thu Dec 28 13:04:39 2017

Adding Methylation Levels
Thu Dec 28 13:04:39 2017

Done
Thu Dec 28 13:04:39 2017
```

Thanks, 
Rahul

**Comment by yupenghe** [comment]
Hi Rahul,
It seems no site was tested. Is run4_rms_results.tsv empty? 

If you previous tried to [test methylpy](https://github.com/yupenghe/methylpy#test-methylpy), did you get any error regarding DMRfind? If you haven't tried, I would recommend to do that first. It will take only a few minutes. 

Yupeng

**Comment by rbpisupati** [comment]
Thanks Yupeng for a prompt reply. The DMRfind tests are failed. Doesnt seem to be an installation problem. Can you help me with this?
```
>  python run_test.py
Tests start
Thu Dec 28 18:53:27 2017

Test importing methylpy module.
- importing call_mc_se: pass
- importing call_mc_pe: pass
- importing DMRfind: pass
- importing parser: pass
Check methylpy executable:pass

methylpy is successfully installed!

Check whether dependencies are available in PATH
- find bowtie: found version 1.1.2
- find bowtie2: found version 2.3.2
- find samtools: found version 1.6
- find cutadapt: found version 1.14
- find java: found version 1.8.0_131
Both bowtie and bowtie2 are available and will be tested.

Test DMRfind: failed
Test reidentify-DMR: failed

Test build-reference with bowtie: pass
Test build-reference with bowtie2: pass

Test single-end-pipeline with bowtie: pass
Test single-end-pipeline with bowtie2: pass

Test paired-end-pipeline with bowtie: pass
Test paired-end-pipeline with bowtie2: pass

Test quality filter for BAM file of single-end data: pass

Test call-methylation-state for single-end data: pass
Test call-methylation-state for paired-end data: pass

Test merge-allc: pass

Test filter-allc: pass

All tests are done!
Thu Dec 28 18:55:58 2017
The tests took 151.81 seconds!
```

Thanks again, 
Rahul

**Comment by yupenghe** [comment]
It is likely that you will need to go through this [step](https://github.com/yupenghe/methylpy#optional-step---compile-rmscpp) to install the GSL library (and potentially recompile the rms.cpp if DMRfind still fails).

**Comment by rbpisupati** [comment]
We have tested this while installation. It seems to work fine.

```
> run_rms_tests.out
Usage: ./rms.out <chunk files> <output file> <samples> <min_cov> <num_sims> <num_sig_tests> <seed>
```

**Comment by yupenghe** [comment]
ok. Glad to know the run_rms_tests.out is working well. Are you using the latest methylpy? If DMRfind still fails after updating methylpy to latest version, can you share me with the test_error_msg.txt and test_output_msg.txt in the methylpy_test/ folder (where you tested methylpy)? Thanks.

**Comment by rbpisupati** [comment]
I am attaching the files below.

[test_error_msg.txt](https://github.com/yupenghe/methylpy/files/1591953/test_error_msg.txt)
[test_output_msg.txt](https://github.com/yupenghe/methylpy/files/1591954/test_output_msg.txt)

**Comment by yupenghe** [comment]
Thanks. If you do `ls *` and `ls */*` under the methylpy_test folder, what do you see? Can you share the results with me?

What commands you did you use to install methylpy?

**Comment by rbpisupati** [comment]
Here are the files present in the folder. 
```
> ls *
run_test.py  test_error_msg.txt  test_output_msg.txt

chrL:
chrL_f.1.bt2   chrL_f.2.ebwt  chrL_f.4.bt2   chrL_f.rev.1.bt2   chrL_f.rev.2.ebwt  chrL_r.2.bt2   chrL_r.3.ebwt  chrL_r.fasta       chrL_r.rev.2.bt2
chrL_f.1.ebwt  chrL_f.3.bt2   chrL_f.4.ebwt  chrL_f.rev.1.ebwt  chrL_r.1.bt2       chrL_r.2.ebwt  chrL_r.4.bt2   chrL_r.rev.1.bt2   chrL_r.rev.2.ebwt
chrL_f.2.bt2   chrL_f.3.ebwt  chrL_f.fasta   chrL_f.rev.2.bt2   chrL_r.1.ebwt      chrL_r.3.bt2   chrL_r.4.ebwt  chrL_r.rev.1.ebwt

data:
allc_P0_FB_1.tsv.gz      allc_P0_FB_2.tsv.gz      allc_P0_HT_1.tsv.gz      allc_P0_HT_2.tsv.gz      chrL.fa      test_data_R1.fastq.gz
allc_P0_FB_1.tsv.gz.idx  allc_P0_FB_2.tsv.gz.idx  allc_P0_HT_1.tsv.gz.idx  allc_P0_HT_2.tsv.gz.idx  chrL.fa.fai  test_data_R2.fastq.gz

results:
DMR_P0_FBvsHT_filtered_allc_P0_FB_1.tsv          DMR_P0_FBvsHT_filtered_allc_P0_HT_2.tsv          allc_se_bt.tsv.gz.idx
DMR_P0_FBvsHT_filtered_allc_P0_FB_1.tsv.idx      DMR_P0_FBvsHT_filtered_allc_P0_HT_2.tsv.idx      allc_se_bt2.tsv.gz
DMR_P0_FBvsHT_filtered_allc_P0_FB_1.tsv_1_0      DMR_P0_FBvsHT_filtered_allc_P0_HT_2.tsv_1_0      allc_se_bt2.tsv.gz.idx
DMR_P0_FBvsHT_filtered_allc_P0_FB_1.tsv_1_0.tsv  DMR_P0_FBvsHT_filtered_allc_P0_HT_2.tsv_1_0.tsv  pe_bt2_processed_reads.bam
DMR_P0_FBvsHT_filtered_allc_P0_FB_2.tsv          allCG_P0_FB_1.tsv.gz                             pe_bt_processed_reads.bam
DMR_P0_FBvsHT_filtered_allc_P0_FB_2.tsv.idx      allc_merged.tsv.gz                               se_bt2_processed_reads.bam
DMR_P0_FBvsHT_filtered_allc_P0_FB_2.tsv_1_0      allc_merged.tsv.gz.idx                           se_bt2_processed_reads.bam.bai
DMR_P0_FBvsHT_filtered_allc_P0_FB_2.tsv_1_0.tsv  allc_pe_bt.tsv.gz                                se_bt2_processed_reads.filtered.bam
DMR_P0_FBvsHT_filtered_allc_P0_HT_1.tsv          allc_pe_bt.tsv.gz.idx                            se_bt_processed_reads.bam
DMR_P0_FBvsHT_filtered_allc_P0_HT_1.tsv.idx      allc_pe_bt2.tsv.gz                               se_bt_processed_reads.bam.bai
DMR_P0_FBvsHT_filtered_allc_P0_HT_1.tsv_1_0      allc_pe_bt2.tsv.gz.idx                           se_bt_processed_reads.filtered.bam
DMR_P0_FBvsHT_filtered_allc_P0_HT_1.tsv_1_0.tsv  allc_se_bt.tsv.gz

```

**Comment by yupenghe** [comment]
Thanks. Can you try your previous command
```
methylpy DMRfind --allc-files allc_temp17.tsv.gz allc_temp18.tsv.gz allc_temp19.tsv.gz allc_temp20.tsv.gz --samples temp17 temp18 temp19 temp20 --mc-type CG --num-procs 8 --output-prefix run4
```

but with the value of "--mc-type" changed from "CG" to "CGN"?

**Comment by rbpisupati** [comment]
I did try changing the --mc-type option but still go the same result.

**Comment by yupenghe** [comment]
That is weird. If you run the below command in `methylpy_test` (where you tested methylpy), what do you get?

```
methylpy DMRfind --allc-files data/allc_P0_FB_1.tsv.gz data/allc_P0_FB_2.tsv.gz data/allc_P0_HT_1.tsv.gz data/allc_P0_HT_2.tsv.gz --samples P0_FB_1 P0_FB_2 P0_HT_1 P0_HT_2 --mc-type CGN --num-procs 8 --output-prefix DMR_test
```

**Comment by Papareddy** [comment]
Just wanted to add a comment I am also having the same issue .. when I run a week back  DMRfind I got exactly the same errors .. I am also from the same institute.. does it mean some problem with installion on our HPC?

**Comment by yupenghe** [comment]
I see. Could you provide more details? What was the command you used? Did you test methylpy and did DMRfind pass the test?

**Comment by Papareddy** [comment]
methylpy DMRfind --allc-files WT_ht_pool.tsv P4-HT_pool.tsv --samples WT P4 --mc-type CHH --num-procs 16 --output-prefix CHH

I have run the methylpy_test command and I got exactly like Rahul... @rbpisupati even after manual loading of bowtie along with default bowtie2 with methylpy ..
![methylpy_test](https://user-images.githubusercontent.com/33577042/34456459-0a847560-ed97-11e7-998b-42e90f8a5b23.jpeg)
tests for DMRfind and reidentify-DMR are failed

**Comment by yupenghe** [comment]
Thanks. Can you also share the test_error_msg.txt and test_output_msg.txt file (in the `methylpy_test/` directory) with me?

**Comment by Papareddy** [comment]
please find the attached txt file.. cheers Ranj
[test_output_msg.txt](https://github.com/yupenghe/methylpy/files/1594660/test_output_msg.txt)
[test_error_msg.txt](https://github.com/yupenghe/methylpy/files/1594662/test_error_msg.txt)

**Comment by yupenghe** [comment]
It is indeed the same error. What version of methylpy did you use (you can get it in the setup.py file in the methylpy folder)? If you upgrade methylpy to latest version (pip install --upgrade methylpy), do you still get the same error?

**Comment by Papareddy** [comment]
methylpy/1.1.9

**Comment by Papareddy** [comment]
I will or Rahul will let you know once it got installed

**Comment by yupenghe** [comment]
Thanks. There could be some bug in the earlier version.

**Comment by yupenghe** [comment]
I can finally reproduce the error but I am not sure if the cause I found is the real one. To test this, you may want to try the below commands. 

1. open python console by `python`
2. run the two python commands
```
import methylpy
print(methylpy.__file__[:methylpy.__file__.rfind("/")]+"/run_rms_tests.out")
```
You will see a path on the screen. The path will look like `/YOUR/PATH/methylpy/run_rms_tests.out`. 
3. Check if the file that the path points to actually exists.

**Comment by rbpisupati** [comment]
Yes, you are right. The path do not have the file `run_rms_tests.out`. is that the problem? does it solve if we symbolic link the file which was compiled here?

**Comment by yupenghe** [comment]
It should fix the problem. Can you try that? Also, would you be willing to describe the commands you used to install methylpy? I want to figure out why `run_rms_tests.out` is not there.

**Comment by timeu** [comment]
We installed methylpy on our HPC system with `python.py setup.py install`. But the `run_rms_tests.out` needed to be re-compiled because it was linked to the wrong `libgsl.so.0` files. When re-compiling it I copied the file from the `lib` folder to the `bin` folder where also the other console scripts are located.
This probably caused the issue.

**Comment by yupenghe** [comment]
Thank you. It makes sense. I will add some note to methylpy documents about copying the recompiled executable to methylpy directory. Please let me know if copying the `run_rms_tests.out` to the methylpy directory fix the problem.

**Comment by rbpisupati** [comment]
Yes, changing the executable to the `lib` folder did work! Thanks :)

**Comment by yupenghe** [comment]
Great! Thanks.

**Comment by massfl** [comment]
Hi, 

I have a somewhat similar problem so I figured I would post it here. When runing DMRfind I get a similar error message, In my case the DMR and DMS tsv files contain lists of DM sites and Regions though. The problem seems to be that the FDR calculation is not going through.
"_Begin FDR Correction
Wed Mar 21 22:09:03 2018
m0 estimate for iteration 0: 92070
**Histogram FDR correction did not converge. Using the smallest p-value 0.000333333333333 as cutoff.**
Calculating Residual Cutoff
Wed Mar 21 22:09:04 2018
Begin Defining Windows
Wed Mar 21 22:09:06 2018
Adding Methylation Levels
Wed Mar 21 22:09:08 2018
Done
Wed Mar 21 22:09:08 2018_"

Thanks !

**Comment by massfl** [comment]
I forgot to mention that I am using methylpy 1.3.0

**Comment by yupenghe** [comment]
Hi, did you get empty results as well? The FDR calculation did not go through if there are too few regions showing differential methylation. So, methylpy will report the most significant methylation differences (that do not pass FDR cutoff).

**Comment by XiaonanG** [comment]
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/45122582/80580944-f0c0e400-8a3e-11ea-8cd8-cda8e164aa84.png">
Hi Yupeng, I also have the same problem as shown in the figure. I found there is a # before chr in the DMR_rms_resultes_collapsed.tsv file, is it correct? I checked the  run_rms_tests.out file, it is in the lib folder and I installed the methylpy by pip install methylphy. Would you like to give me some suggestions?
