### ISSUE TITLE
PATH to Picard

### ISSUE THREAD

**Issue by olmath** [yupenghe/methylpy#60]
Hi,

I have been installing methylpy through conda and I have a problem using the path-to-picard parameter.
I copy/paste the `which picard` output to the `path-to-picard` parameter but this doesn't work.
Can you help?

Many thank

**Comment by yupenghe** [comment]
Hi, methylpy has not been modified to use the picard that is installed as executable. It looks for `picard.jar`. You can download the jar file (`picard.jar`) from picard's website

https://github.com/broadinstitute/picard/releases/latest

Then, pointing methylpy to the folder that contains `picard.jar` should work. For example, if the downloaded `picard.jar` is in `/home/AAA/`, we can run methylpy by passing `/home/AAA/` to the `path-to-picard` paramerer.
