### ISSUE TITLE
multiple core problems

### ISSUE THREAD

**Issue by coralzhang** [yupenghe/methylpy#61]
Hi, 

I am using the methylpy to add methylation levels. I called number of procs as follows
```
methylpy add-methylation-level \
	--input-tsv-file /xx/xx/_short_window1h.tsv \
	--output-file $outfile \
	--allc-files allc_1_wbed.tsv.gz allc_2_wbed.tsv.gz \
	--samples 1 2 \
	--mc-type $mctype \
	--num-procs 5 \
     1>$stdoutfile1 2>$errfile1
```
But, I only see 2 processes in top  showing this job. Any thoughts why? I tried reinstall, and that did not change this... Any thoughts? Thanks a lot
I have 
methylpy --version
1.4.2

**Comment by yupenghe** [comment]
The multiprocessing is by samples. Since there are only two input samples, at most 2 cores will be used. This is expected.

**Comment by coralzhang** [comment]
Hi 
Per this add methylation level function, are there anyways to make it faster if I only have 2 samples but a huge number of tiny regions I need to add levels for? Thanks!

**Comment by yupenghe** [comment]
One way to do this is to split the regions into separate files, run one methylpy command on each of them, and after all the runs, combine the outputs.

**Comment by coralzhang** [comment]
Makes sense. Thanks!
