### ISSUE TITLE
Where is the methylation difference reflected in the DMRfind code

### ISSUE THREAD

**Issue by BTSARMY0613** [yupenghe/methylpy#65]
Hi yupenghe:
    I found  the methylation difference is greater than or equal to 0.3 in at least one of the pairwise comparisons are  retained while reading the paper. But I can't find the cutoff(0.3) in your code. I want to know where this cutoff is reflected in the code, and where is Ziller's method reflected in the python code?

![image](https://user-images.githubusercontent.com/49978834/109122406-82929e00-7783-11eb-8ffa-6400a1ceeec4.png)

**Comment by yupenghe** [comment]
The 0.3 cutoff was applied after getting the DMR results from methylpy. The code for running Ziller et al's method is available in this website (associated with the paper).
http://neomorph.salk.edu/human_tissue_methylomes.html

**Comment by BTSARMY0613** [comment]
That is to say, the methylation difference is not involved in the methylpy python code but involved in the Ziller's R code？ Do I need to run Ziller's R code again to get the final DMR result ?

**Comment by yupenghe** [comment]
Just to be clear. There are two sets of DMRs in the paper and both of them are available in the page posted above (specially code and DMRs can be downloaded [here](http://neomorph.salk.edu/SDEC_tissue_methylomes/processed_data/code_data.tar.gz)). The two sets of DMRs are from
* methylpy + 0.3 methylation different filter posted afterwards
* Ziller's code which intrinsically includes the 0.3 filter

**Comment by BTSARMY0613** [comment]
Thank you very much for your answer. I didn't seem to understand the paper correctly before.
In other words, I used methylpy to get a result file(g1_g2_rms_results_collapsed.tsv.DMR), and this file stores DMR information, but this DMR is not filtered by methylation different. After I get this file, I need to perform another operation on it to finally get the DMR filtered by methylation different. Is my understanding correct?
Now I want to control the methylation different to be 0.2 or another number, how should I do it? So far I have got some results using methylpy.

**Comment by yupenghe** [comment]
That is correct. For further filtering, it is more about how to define the methylation difference (mean, median etc) and then we could apply a threshold.

**Comment by BTSARMY0613** [comment]
I understand, thank you very much for your answer.
But now I have a question about the sample-category option in DMRfind. I found that this option has a great influence on my results. If this option is specified, the DMR obtained will be much less.
Look at the explanation of this option，It means space-separated sample group names for specifying which samples are considered as replicates.
For this replicates, I would like to ask, for example, there are 10 samples in total, 5 of which belong to the same category, and 5 belong to another category. Do 5 samples belonging to the same category need to be regarded as replicates?

**Comment by yupenghe** [comment]
You are right about the `--sample-category` option. This option is not required. If you want methylpy to treat the samples as individual samples, this option can be ignored. It is more of a choice for the user. Does this answer your question?

**Comment by BTSARMY0613** [comment]
Yeah, I understand, thank you very much for your answer.
And now I have some questions about the result file "_rms_results_collapsed.tsv.DMS" and pvalue cutoff.
 
- Is this file all the DMS information obtained?I see this in this file and I want to know if the fifth column is pvalue.
<img width="278" alt="微信图片_20210305214210" src="https://user-images.githubusercontent.com/49978834/110123275-ae54fa00-7dfb-11eb-8fd6-5d2d4d11cd91.png">
- If the fifth column is pvalue, I found that many DMSs have pvalue greater than 0.01, which is not very significant. If it is not significant, can the site be considered as DMS?
- I see that the methylpy method in the supplementary file of the paper does not directly use pvalue<0.01 as the cutoff to determine DMS, and need to calculate the cutoff of pvalue, right? That is, the cutoff of the final pvalue is not necessarily 0.01. Is my understanding correct?

I am currently comparing three methods to find DMR, and then the other two methods use pvalue and methylation difference as the threshold. In the past few days, I have figured out how your method uses methylation differences to screen DMR, and now I am a little confused about the pvalue of the methylpy method.  It feels impossible to compare the three methods with a unified threshold. 
Thank you very much for your patience to answer my confusion

**Comment by BTSARMY0613** [comment]
Yeah, I understand, thank you very much for your answer.
And now I have some questions about the result file "_rms_results_collapsed.tsv.DMS" and pvalue cutoff.

- Is this file all the DMS information obtained?I see this in this file and I want to know if the fifth column is pvalue.
<img width="278" alt="微信图片_20210305214210" src="https://user-images.githubusercontent.com/49978834/110125213-07be2880-7dfe-11eb-8d82-691cf5463d46.png">

- If the fifth column is pvalue, I found that many DMSs have pvalue greater than 0.01, which is not very significant. If it is not significant, can the site be considered as DMS?

- I see that the methylpy method in the supplementary file of the paper does not directly use pvalue<0.01 as the cutoff to determine DMS, and need to calculate the cutoff of pvalue, right? That is, the cutoff of the final pvalue is not necessarily 0.01. Is my understanding correct?

I am currently comparing three methods to find DMR, and then the other two methods use pvalue and methylation difference as the threshold. In the past few days, I have figured out how your method uses methylation differences to screen DMR, and now I am a little confused about the pvalue of the methylpy method. It feels impossible to compare the three methods with a unified threshold.
Thank you very much for your patience to answer my confusion

**Comment by yupenghe** [comment]
Yes, the file contains the information about all DMSs and yes, the 5th column is p-value. There is more information in `_rms_results.tsv.gz`, which includes details about all tested sites.

It depends on the value passed to the `--sig-cutoff` option. For example, if we use 0.05, then the results may contain sites with p-value greater than 0.01 (but should be smaller than 0.05).

Methylpy does FDR multiple testing correction to get the p-value cutoff that should suffice the FDR. `--sig-cutoff` is the FDR level that we want to control for.

**Comment by BTSARMY0613** [comment]
But after I set `--sig-cutoff` to 0.01, I still get a lot of DMS p-values greater than 0.01. I see this "The closest p-value cutoff for your desired FDR is 0.14204545454545456 which corresponds to an FDR of 0.00999096950501593" in my test output file. That is to say, the p value calculated after setting the FDR level to 0.01 is less than 0.14204545454545456. Am I right？
I see this in your code, but I did not find this article based on the URL you gave.
![image](https://user-images.githubusercontent.com/49978834/110286369-c5743180-801f-11eb-95a9-ed8e72b3cccd.png)
Could you please post the valid URL of this article again? I want to see the method about how to calculate the pvalue cutoff for a particular FDR.

**Comment by BTSARMY0613** [comment]
Oh I find the article, thank you!
