### ISSUE TITLE
Average methylation level of a sample

### ISSUE THREAD

**Issue by connorrogerson** [yupenghe/methylpy#66]
Is there a way to get the average methylation level of a sample without going through the whole pipeline? Ideally I'd just want an output something similar to:
Sample methylation 
Sample_1 34% 
Sample_2 36% 
Sample_3 68% 
Sample_4 59%

**Comment by yupenghe** [comment]
The simplest way is to use the allc file directly. I assume that you want to calculate the global CpG methylation level. You can do
```
gzip -dc YOUR_ALLC_FILE | awk '$4 ~ /^CG/ {mc+=$5;h+=$6} END {print mc/h}'
```
