### ISSUE TITLE
DMRfind fails with key error 179

### ISSUE THREAD

**Issue by georgback** [yupenghe/methylpy#67]
When running methylpy DMRfind with the --chroms argument the program fails with 
```

Splitting allc files for chromosome 1

<class 'KeyError'> 179
'1'
Running RMS tests failed.

```
This happens for any chromosome at the first position (i.E. <class 'KeyError'> 179 '2'  for --chroms 2 )

if no --chroms argument is given, the program finishes, but creates empty result files only containing the headers.

The filtered_allc files created before the programs fails seem to be filtered correctly depending on the --chroms and --mc-type. The idx files however only contain #eof

methylpy version : 1.4.6
python: 3.8

OS: Ubuntu 16.04

**Comment by yupenghe** [comment]
The key issue is "The idx files however only contain #eof". Would reindex the allc file (like below) give a different idx file? If so, does it solve the problem?
```
methylpy index-allc \
	--allc-files allc/allc_AD_HT_1.tsv.gz allc/allc_AD_HT_2.tsv.gz \
	--num-procs 2 \
	--no-reindex False
```

If that still does not work, do you mind to share the first few lines of the allc file you have?

**Comment by georgback** [comment]
Manually running index-allc solved the issue.

Thank you very much.
