### ISSUE TITLE
TMP DIR for the picard tools

### ISSUE THREAD

**Issue by rbpisupati** [yupenghe/methylpy#7]
Hello Yupeng, 

Can you set TMP DIR option in [remove_clonal_bam](https://github.com/yupenghe/methylpy/blob/methylpy/methylpy/call_mc_se.py#L1319) function? It is raising some writing errors.

something like this since TMPDIR can be set by user easily.
`-Djava.io.tmpdir=$TMPDIR`

Rahul

**Comment by yupenghe** [comment]
Is it something that can be done using the `java_options` parameter?

**Comment by rbpisupati** [comment]
Yes, it can be done using java_options. thanks! :)

**Comment by yupenghe** [comment]
Great!
