### ISSUE TITLE
Ubuntu Optional step to Compile rms.cpp is formatted wrong

### ISSUE THREAD

**Issue by adioni** [yupenghe/methylpy#71]
The example g++ command to run on Ubuntu systems has an em-dash in front of libs and will results in error messages if one just copies and pastes it in to the command line:

BAD:
```
g++ -o run_rms_tests.out rms.cpp `gsl-config --cflags —libs` 
```

GOOD:
```
g++ -o run_rms_tests.out rms.cpp `gsl-config --cflags --libs` 
```

**Comment by yupenghe** [comment]
Thanks for catching that. I just fixed this typo.
