### ISSUE TITLE
DMRfind-Histogram FDR correction did not converge.

### ISSUE THREAD

**Issue by nnlrl** [yupenghe/methylpy#79]
Hi.
Recently, I was using methylpy for DMR analysis. I found that every time I call DMRfind, the log will print `Histogram FDR correction did not convert Using the smallest p-value 0.0003333333333333333 as cutoff.` (even if I use the test data in the tutorial). But I can get DMS and DMR result normally (about 3 million DMS in CG_rms_results_collapsed.tsv.DMS.bed). I don't know what this represents and whether it will affect the results

```
Begin FDR Correction
Sun Oct  9 14:38:45 2022

m0 estimate for iteration 0: 45840764
Histogram FDR correction did not converge. Using the smallest p-value 0.0003333333333333333 as cutoff.

Calculating Residual Cutoff
Sun Oct  9 14:39:30 2022

Begin Defining Windows
Sun Oct  9 14:39:41 2022

Adding Methylation Levels
Sun Oct  9 14:43:42 2022

Done
Sun Oct  9 14:48:25 2022
```

**Comment by yupenghe** [comment]
Hey it would be fine to use the results. The FDR method sometimes does not converge and in that case, the recommendation is to use the smallest p-value as the threshold (as a conservative workaround).
