### ISSUE TITLE
Merging of allc files

### ISSUE THREAD

**Issue by rbpisupati** [yupenghe/methylpy#9]
Hi, 

Merging of allc files doesnt sort the generated final allc file, will that be a problem during DMR calling? Also can you add an option to run binomial test for the generated file?

Rahul

**Comment by yupenghe** [comment]
Hi Rahul,
Just want to be clear: the sites final (merged) allc file are sorted by chromosome and position but the order of chromosomes is uncertain. 

It will not cause problem in DMR calling. 

Yes. I will consider adding binomial test feature for the final allc file. 

Yupeng

**Comment by yupenghe** [comment]
Just want to let you know. The binomial test is now a feature in methylpy.
